version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - brassbook_db

  brassbook_db:
    image: postgres:13.4-alpine
    ports:
      - "5432:5432"
    user: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    healthcheck:
      test: ["CMD", "pg_isready"]
      timeout: 45s
      interval: 10s
      retries: 1

volumes:
  db_data: